version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      # Restore bundle cache
#      - restore_cache:
#          keys:
#            - rails-demo-{{ checksum "Gemfile.lock" }}
#            - rails-demo-
      - run:
          name: Install dependencies
          command: bundle check || bundle install --jobs 4 --retry 3
#      - save_cache:
#          key: rails-demo-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle
      - run:
          name: Unit Tests
          command: bundle exec rake spec
      - run:
          name: Link Checker
          command: ./check-links.sh
